### 기초 선언

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

### 가중치W 0으로 초기화
### 편향b 0으로 초기화
tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)
[0.]가 0을 의미한다 그리고 requires_grad=True는 동시에 기울기 계산이 가능하다는 의미이다.

In [6]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
W = torch.zeros(1, requires_grad=True) 
b = torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


### 가설과 함수비용

In [8]:
hypothesis = x_train * W + b
print(hypothesis)
cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
tensor(18.6667, grad_fn=<MeanBackward0>)


In [9]:
optimizer = optim.SGD([W, b], lr=0.01)
nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  100/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  200/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  300/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  400/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  500/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  600/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  700/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  800/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  900/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1000/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1100/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1200/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1300/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1400/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1500/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1600/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1700/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1800/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1900/1999 W: 0.000, b: 0.

### 다중 선형 회귀 구현하기 ###

In [3]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])


In [4]:

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))


Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079378
