### 기초 선언

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

### 가중치W 0으로 초기화
### 편향b 0으로 초기화
tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)
[0.]가 0을 의미한다 그리고 requires_grad=True는 동시에 기울기 계산이 가능하다는 의미이다.

In [6]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
W = torch.zeros(1, requires_grad=True) 
b = torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


### 가설과 함수비용

In [8]:
hypothesis = x_train * W + b
print(hypothesis)
cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
tensor(18.6667, grad_fn=<MeanBackward0>)


In [9]:
optimizer = optim.SGD([W, b], lr=0.01)
nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  100/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  200/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  300/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  400/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  500/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  600/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  700/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  800/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  900/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1000/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1100/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1200/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1300/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1400/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1500/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1600/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1700/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1800/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1900/1999 W: 0.000, b: 0.