In [33]:
import torch

# 입력값과 정답값
x = torch.ones(5)  # 입력 텐서
y = torch.zeros(3)  # 정답 텐서

# 가중치 및 편향 (requires_grad=True 설정)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)

# 선형 변환 (z = x * w + b)
z = torch.matmul(x, w) + b

# 손실 함수 (Binary Cross Entropy with Logits)
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

# 변화도 출력
print(w)
print(b)


tensor([[ 0.6035, -1.1151, -1.8547],
        [ 2.1064, -0.5506,  1.7297],
        [ 0.8686, -0.8914,  0.6844],
        [ 0.5296,  0.2244, -0.3527],
        [-0.3780, -0.0345, -2.6298]], requires_grad=True)
tensor([0.2397, 0.5736, 0.3549], requires_grad=True)


In [24]:
print(f"Gradient function for z = {z.grad_fn}")  
print(f"Gradient function for loss = {loss.grad_fn}")


Gradient function for z = <AddBackward0 object at 0x000001EEF0F53B20>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001EEF0F523E0>


In [34]:
loss.backward()  # 역전파 실행
print(w)
print(b)
# 변화도 출력
print(w.grad)
print(b.grad)


tensor([[ 0.6035, -1.1151, -1.8547],
        [ 2.1064, -0.5506,  1.7297],
        [ 0.8686, -0.8914,  0.6844],
        [ 0.5296,  0.2244, -0.3527],
        [-0.3780, -0.0345, -2.6298]], requires_grad=True)
tensor([0.2397, 0.5736, 0.3549], requires_grad=True)
tensor([[0.3272, 0.0475, 0.0374],
        [0.3272, 0.0475, 0.0374],
        [0.3272, 0.0475, 0.0374],
        [0.3272, 0.0475, 0.0374],
        [0.3272, 0.0475, 0.0374]])
tensor([0.3272, 0.0475, 0.0374])


In [26]:
z = torch.matmul(x, w) + b  # requires_grad=True인 상태
print(z.requires_grad)  # True 출력

# 연산 기록 비활성화
with torch.no_grad():
    z = torch.matmul(x, w) + b

print(z.requires_grad)  # False 출력


True
False


In [27]:
z = torch.matmul(x, w) + b
z_det = z.detach()  # 그래프에서 분리
print(z_det.requires_grad)  # False 출력


False


In [28]:
for i in range(3):
    x = torch.randn(2, 2, requires_grad=True)
    y = x * 3
    loss = y.sum()
    loss.backward()
    print(x.grad)  # 매번 다른 값 출력


tensor([[3., 3.],
        [3., 3.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[3., 3.],
        [3., 3.]])


In [29]:
inp = torch.eye(4, 5, requires_grad=True)  # 4x5 단위 행렬
out = (inp + 1).pow(2).t()  # 전치 행렬 연산
out.backward(torch.ones_like(out), retain_graph=True)

print(inp.grad)  # 변화도 출력


tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])


In [30]:
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")  # 변화도가 두 배로 증가

inp.grad.zero_()  # 변화도 초기화
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")  # 올바른 변화도 출력



Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
