### 기초 선언

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

### 가중치W 0으로 초기화
### 편향b 0으로 초기화
tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)
[0.]가 0을 의미한다 그리고 requires_grad=True는 동시에 기울기 계산이 가능하다는 의미이다.

In [6]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
W = torch.zeros(1, requires_grad=True) 
b = torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


### 가설과 함수비용

In [8]:
hypothesis = x_train * W + b
print(hypothesis)
cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
tensor(18.6667, grad_fn=<MeanBackward0>)


In [9]:
optimizer = optim.SGD([W, b], lr=0.01)
nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  100/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  200/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  300/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  400/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  500/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  600/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  700/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  800/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch  900/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1000/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1100/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1200/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1300/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1400/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1500/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1600/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1700/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1800/1999 W: 0.000, b: 0.000 Cost: 18.666666
Epoch 1900/1999 W: 0.000, b: 0.

### 다중 선형 회귀 구현하기 ###

In [6]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])


In [9]:

# 모델 초기화 0으로 초기화 한다는 뜻
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))


Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670898
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.482086
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

In [8]:
# 임의의 입력 값에 대한 예측
with torch.no_grad():
    new_input = torch.FloatTensor([[75, 85, 72]])  # 예측하고 싶은 임의의 입력
    prediction = new_input.matmul(W) + b
    print('Predicted value for input {}: {}'.format(new_input.squeeze().tolist(), prediction.item()))


Predicted value for input [75.0, 85.0, 72.0]: 156.8051300048828
