### 기초 선언

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

### 가중치W 0으로 초기화
### 편향b 0으로 초기화
tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)
[0.]가 0을 의미한다 그리고 requires_grad=True는 동시에 기울기 계산이 가능하다는 의미이다.

In [6]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
W = torch.zeros(1, requires_grad=True) 
b = torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


### 가설과 함수비용

In [8]:
hypothesis = x_train * W + b
print(hypothesis)
cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
tensor(18.6667, grad_fn=<MeanBackward0>)


1. optimizer.zero_grad()
목적: 기울기 초기화
설명:
PyTorch에서는 **기울기(gradient)**가 누적됩니다. 즉, backward()가 여러 번 호출될 때마다 기울기가 기존의 기울기 값에 계속 더해지게 됩니다.
따라서, 새로운 기울기 계산을 시작하기 전에 기존의 기울기를 초기화해야 합니다.
optimizer.zero_grad()는 이를 수행하여 이전 기울기를 모두 초기화합니다.
예시:

만약 optimizer.zero_grad() 없이 backward()를 여러 번 호출하면, 첫 번째 backward()에서 계산된 기울기가 누적되므로, 두 번째 호출에서 잘못된 기울기가 계산될 수 있습니다.

2. cost.backward()
목적: 기울기 계산 (역전파)
설명:
cost.backward()는 손실 함수(cost)에 대한 기울기를 각 파라미터에 대해 계산합니다.
여기서 "기울기"는 손실 함수가 각 파라미터(예: W, b)에 대해 얼마나 민감한지를 나타내는 값입니다. 즉, 파라미터의 작은 변화가 손실에 어떤 영향을 미치는지를 나타냅니다.
backward()는 자동으로 미분을 수행하여 기울기를 계산하고, 계산된 기울기는 각 파라미터의 .grad 속성에 저장됩니다.
예시:

W.grad에는 W에 대한 기울기가, b.grad에는 b에 대한 기울기가 저장됩니다.
이 기울기는 가중치 업데이트에 사용됩니다.

3. optimizer.step()
목적: 가중치 업데이트
설명:
optimizer.step()은 기울기를 사용하여 가중치를 업데이트합니다. 즉, 경사 하강법(또는 다른 최적화 알고리즘)에 따라 파라미터를 조정합니다.
optimizer.step()은 계산된 기울기를 바탕으로 가중치를 업데이트합니다. 보통 W = W - lr * W.grad와 같은 방식으로 업데이트됩니다. lr은 학습률입니다.
step()이 실행된 후, 가중치는 기울기 방향으로 조정됩니다.
예시:

W와 b는 기울기를 반영하여 업데이트됩니다.
예를 들어, optimizer.step()이 호출되면, W와 b는 **학습률(lr)**에 따라 기울기 방향으로 조정됩니다.


In [11]:
optimizer = optim.SGD([W, b], lr=0.01)
nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 1.997, b: 0.006 Cost: 0.000005
Epoch  100/1999 W: 1.998, b: 0.005 Cost: 0.000003
Epoch  200/1999 W: 1.998, b: 0.004 Cost: 0.000002
Epoch  300/1999 W: 1.999, b: 0.003 Cost: 0.000001
Epoch  400/1999 W: 1.999, b: 0.002 Cost: 0.000001
Epoch  500/1999 W: 1.999, b: 0.002 Cost: 0.000000
Epoch  600/1999 W: 1.999, b: 0.001 Cost: 0.000000
Epoch  700/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  800/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  900/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1000/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1100/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1200/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1300/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1400/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1500/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1600/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1700/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1800/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1900/1999 W: 2.000, b: 0.000 Cost: 0.000000
